version: "3.8"
services:
  database:
    container_name: book-database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-service
    ports:
      - "5433:5432"